# Generated by Django 4.1.1 on 2022-09-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='type',
            new_name='restaurant_type',
        ),
    ]
