# Generated by Django 4.1.1 on 2022-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_type_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='search_terms',
            field=models.CharField(default='<django.db.models.fields.CharField>,<django.db.models.fields.CharField>', max_length=500),
        ),
    ]
