# Generated by Django 4.1.1 on 2022-09-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_remove_dish_ingredients_ingredient_dishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dishes',
        ),
    ]
