# Generated by Django 4.1.1 on 2022-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_ingredient_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='dishes',
            field=models.ManyToManyField(to='menu.dish'),
        ),
    ]
